/* species-data.js — מאגר פרטי המינים (מקור: קובץ ה-PDF של המשתמש).
 * לכל מין: שם עברי, שם אנגלי, שם מדעי (לטיני) ומשפחה.
 * משמש את טאב "מינים" להצגת רשימת המינים עם פרטים.
 */
export const SPECIES_DATA = [
  { he: 'אווזון קטן / ברווז שורק קטן', en: '', sci: '', family: '' },
  { he: 'ברנטה אדומת-חזה', en: 'Red-breasted Goose', sci: 'Branta ruficollis', family: 'ברווזים' },
  { he: 'ברנטה לבנת־לחיים', en: 'Barnacle Goose', sci: 'Branta leucopsis', family: 'ברווזים' },
  { he: 'אווז אפור', en: 'Greylag Goose', sci: 'Anser anser', family: 'ברווזים' },
  { he: 'אווז אחו טאיגה', en: 'Taiga Bean Goose', sci: 'Anser fabalis', family: 'ברווזים' },
  { he: 'אווז אחו טונדרה', en: 'Tundra Bean Goose', sci: 'Anser serrirostris', family: 'ברווזים' },
  { he: 'אווז לבן מצח', en: 'Greater White-fronted Goose', sci: 'Anser albifrons', family: 'ברווזים' },
  { he: 'אווז קטן', en: 'Lesser White-fronted Goose', sci: 'Anser erythropus', family: 'ברווזים' },
  { he: 'ברבור מצוי', en: 'Mute Swan', sci: 'Cygnus olor', family: 'ברווזים' },
  { he: 'ברבור קטן', en: 'Tundra Swan', sci: 'Cygnus columbianus', family: 'ברווזים' },
  { he: 'ברבור שר', en: 'Whooper Swan', sci: 'Cygnus cygnus', family: 'ברווזים' },
  { he: 'יאורית מצרית', en: 'Egyptian Goose', sci: 'Alopochen aegyptiaca', family: 'ברווזים' },
  { he: 'טדורנה ירוקת ראש', en: 'Common Shelduck', sci: 'Tadorna tadorna', family: 'ברווזים' },
  { he: 'קזרקה חלודית', en: 'Ruddy Shelduck', sci: 'Tadorna ferruginea', family: 'ברווזים' },
  { he: 'ברבר', en: 'Muscovy Duck', sci: 'Cairina moschata', family: 'ברווזים' },
  { he: 'קרקיר', en: 'Garganey', sci: 'Spatula querquedula', family: 'ברווזים' },
  { he: 'מרית צפונית', en: 'Northern Shoveler', sci: 'Spatula clypeata', family: 'ברווזים' },
  { he: 'ברווז אפור', en: 'Gadwall', sci: 'Mareca strepera', family: 'ברווזים' },
  { he: 'ברווז צהוב מצח', en: 'Eurasian Wigeon', sci: 'Mareca penelope', family: 'ברווזים' },
  { he: 'ברכייה', en: 'Mallard', sci: 'Anas platyrhynchos', family: 'ברווזים' },
  { he: 'שרשיר הכף', en: 'Cape Teal', sci: 'Anas capensis', family: 'ברווזים' },
  { he: 'שרשיר אדום-מקור', en: 'Red-billed Teal', sci: 'Anas erythrorhyncha', family: 'ברווזים' },
  { he: 'ברווז חד-זנב', en: 'Northern Pintail', sci: 'Anas acuta', family: 'ברווזים' },
  { he: 'שרשיר מצוי', en: 'Eurasian Teal', sci: 'Anas crecca', family: 'ברווזים' },
  { he: 'ברווז משויש', en: 'Marbled Duck', sci: 'Marmaronetta angustirostris', family: 'ברווזים' },
  { he: 'נטה אדומת-ראש', en: 'Red-crested Pochard', sci: 'Netta rufina', family: 'ברווזים' },
  { he: 'צולל דרומי', en: 'Southern Pochard', sci: 'Netta erythrophthalma', family: 'ברווזים' },
  { he: 'צולל חלודי', en: 'Common Pochard', sci: 'Aythya ferina', family: 'ברווזים' },
  { he: 'צולל ביצות', en: 'Ferruginous Duck', sci: 'Aythya nyroca', family: 'ברווזים' },
  { he: 'צולל מצויץ', en: 'Tufted Duck', sci: 'Aythya fuligula', family: 'ברווזים' },
  { he: 'צולל ימי', en: 'Greater Scaup', sci: 'Aythya marila', family: 'ברווזים' },
  { he: 'אדרית שחורת-כיפה', en: 'Common Eider', sci: 'Somateria mollissima', family: 'ברווזים' },
  { he: 'קטיפנית שחומה', en: 'Velvet Scoter', sci: 'Melanitta fusca', family: 'ברווזים' },
  { he: 'ברווז קרח', en: 'Long-tailed Duck', sci: 'Clangula hyemalis', family: 'ברווזים' },
  { he: 'עבראש ירוק', en: 'Common Goldeneye', sci: 'Bucephala clangula', family: 'ברווזים' },
  { he: 'מרגון גמדי', en: 'Smew', sci: 'Mergellus albellus', family: 'ברווזים' },
  { he: 'מרגון גדול', en: 'Common Merganser', sci: 'Mergus merganser', family: 'ברווזים' },
  { he: 'מרגון בינוני', en: 'Red-breasted Merganser', sci: 'Mergus serrator', family: 'ברווזים' },
  { he: 'צח-ראש לבן', en: 'White-headed Duck', sci: 'Oxyura leucocephala', family: 'ברווזים' },
  { he: 'פרנקולין שחור', en: 'Black Francolin', sci: 'Francolinus francolinus', family: 'פסיוניים' },
  { he: 'קורא מדברי', en: 'Sand Partridge', sci: 'Ammoperdix heyi', family: 'פסיוניים' },
  { he: 'שליו נודד', en: 'Common Quail', sci: 'Coturnix coturnix', family: 'פסיוניים' },
  { he: 'חוגלת סלעים', en: 'Chukar Partridge', sci: 'Alectoris chukar', family: 'פסיוניים' },
  { he: 'תחמס אירופי', en: 'European Nightjar', sci: 'Caprimulgus europaeus', family: 'תחמסיים' },
  { he: 'תחמס מצרי', en: 'Egyptian Nightjar', sci: 'Caprimulgus aegyptius', family: 'תחמסיים' },
  { he: 'תחמס נובי', en: 'Nubian Nightjar', sci: 'Caprimulgus nubicus', family: 'תחמסיים' },
  { he: 'סיס הרים', en: 'Alpine Swift', sci: 'Tachymarptis melba', family: 'סיסיים' },
  { he: 'סיס חומות', en: 'Common Swift', sci: 'Apus apus', family: 'סיסיים' },
  { he: 'סיס חוורוור', en: 'Pallid Swift', sci: 'Apus pallidus', family: 'סיסיים' },
  { he: 'סיס גליל', en: 'Little Swift', sci: 'Apus affinis', family: 'סיסיים' },
  { he: 'חובה גדולה', en: 'Great Bustard', sci: 'Otis tarda', family: 'חובתיים' },
  { he: 'חוברה מדברית', en: 'Macqueen\'s Bustard', sci: 'Chlamydotis macqueenii', family: 'חובתיים' },
  { he: 'חובה קטנה', en: 'Little Bustard', sci: 'Tetrax tetrax', family: 'חובתיים' },
  { he: 'קוקייה מצוייצת', en: 'Great Spotted Cuckoo', sci: 'Clamator glandarius', family: 'קוקייתיים' },
  { he: 'קוקייה ירוקה / דידריק', en: '', sci: '', family: '' },
  { he: 'קוקייה מזרחית', en: 'Himalayan Cuckoo', sci: 'Cuculus saturatus', family: 'קוקייתיים' },
  { he: 'קוקייה אירופית', en: 'Common Cuckoo', sci: 'Cuculus canorus', family: 'קוקייתיים' },
  { he: 'קטה חדת-זנב', en: 'Pin-tailed Sandgrouse', sci: 'Pterocles alchata', family: 'קטיים' },
  { he: 'קטה סנגלית', en: 'Spotted Sandgrouse', sci: 'Pterocles senegallus', family: 'קטיים' },
  { he: 'קטה גדולה', en: 'Black-bellied Sandgrouse', sci: 'Pterocles orientalis', family: 'קטיים' },
  { he: 'קטת כתר', en: 'Crowned Sandgrouse', sci: 'Pterocles coronatus', family: 'קטיים' },
  { he: 'קטה הודית', en: 'Lichtenstein\'s Sandgrouse', sci: 'Pterocles lichtensteinii', family: 'קטיים' },
  { he: 'יונת סלעים', en: 'Rock Dove', sci: 'Columba livia', family: 'יוניים' },
  { he: 'יונת עצים', en: 'Stock Dove', sci: 'Columba oenas', family: 'יוניים' },
  { he: 'יונת ענק', en: 'Common Wood Pigeon', sci: 'Columba palumbus', family: 'יוניים' },
  { he: 'תור מצוי', en: 'European Turtle Dove', sci: 'Streptopelia turtur', family: 'יוניים' },
  { he: 'תור מזרחי', en: 'Oriental Turtle Dove', sci: 'Streptopelia orientalis', family: 'יוניים' },
  { he: 'תור צווארון', en: 'Eurasian Collared Dove', sci: 'Streptopelia decaocto', family: 'יוניים' },
  { he: 'תור צווארון אפריקני/ ,תור הטבעת', en: '', sci: '', family: '' },
  { he: 'צוצלת', en: 'Laughing Dove', sci: 'Spilopelia senegalensis', family: 'יוניים' },
  { he: 'תורית זנבתנית', en: 'Namaqua Dove', sci: 'Oena capensis', family: 'יוניים' },
  { he: 'רלית המים', en: 'Water Rail', sci: 'Rallus aquaticus', family: 'רליתיים' },
  { he: 'מלכישליו אפריקני', en: 'African Crake', sci: 'Crecopsis egregia', family: 'רליתיים' },
  { he: 'מלכישליו חלודי', en: 'Corn Crake', sci: 'Crex crex', family: 'רליתיים' },
  { he: 'ברודית גדולה', en: 'Spotted Crake', sci: 'Porzana porzana', family: 'רליתיים' },
  { he: 'סופית', en: 'Common Moorhen', sci: 'Gallinula chloropus', family: 'רליתיים' },
  { he: 'אגמית מצויה', en: 'Eurasian Coot', sci: 'Fulica atra', family: 'רליתיים' },
  { he: 'פורפיריה כחולה', en: 'Western Swamphen', sci: 'Porphyrio porphyrio', family: 'רליתיים' },
  { he: 'פורפיריה אפריקנית', en: 'African Swamphen', sci: 'Porphyrio madagascariensis', family: 'רליתיים' },
  { he: 'ברודית גמדית', en: 'Baillon\'s Crake', sci: 'Zapornia pusilla', family: 'רליתיים' },
  { he: 'ברודית קטנה', en: 'Little Crake', sci: 'Zapornia parva', family: 'רליתיים' },
  { he: 'עגור חן', en: 'Demoiselle Crane', sci: 'Grus virgo', family: 'עגוריים' },
  { he: 'עגור אפור', en: 'Common Crane', sci: 'Grus grus', family: 'עגוריים' },
  { he: 'טבלן גמדי', en: 'Little Grebe', sci: 'Tachybaptus ruficollis', family: 'טבלניים' },
  { he: 'טבלן אפור-לחיים', en: 'Red-necked Grebe', sci: 'Podiceps grisegena', family: 'טבלניים' },
  { he: 'טבלן מצויץ', en: 'Great Crested Grebe', sci: 'Podiceps cristatus', family: 'טבלניים' },
  { he: 'טבלן לבן-לחיים', en: 'Horned Grebe', sci: 'Podiceps auritus', family: 'טבלניים' },
  { he: 'טבלן בינוני', en: 'Black-necked Grebe', sci: 'Podiceps nigricollis', family: 'טבלניים' },
  { he: 'פלמינגו גדול', en: 'Greater Flamingo', sci: 'Phoenicopterus roseus', family: 'פלמינגויים' },
  { he: 'פלמינגו זוטר', en: 'Lesser Flamingo', sci: 'Phoeniconaias minor', family: 'פלמינגויים' },
  { he: 'כרוון מצוי', en: 'Eurasian Stone-curlew', sci: 'Burhinus oedicnemus', family: 'כרווניים' },
  { he: 'כרוון סנגלי', en: 'Senegal Thick-knee', sci: 'Burhinus senegalensis', family: 'כרווניים' },
  { he: 'שלצדף החוף', en: 'Eurasian Oystercatcher', sci: 'Haematopus ostralegus', family: 'שלצדפיים' },
  { he: 'תמירון', en: 'Black-winged Stilt', sci: 'Himantopus himantopus', family: 'סייפניים' },
  { he: 'סייפן עקוד', en: 'Pied Avocet', sci: 'Recurvirostra avosetta', family: 'סייפניים' },
  { he: 'קיווית מצוייצת', en: 'Northern Lapwing', sci: 'Vanellus vanellus', family: 'חופמיים' },
  { he: 'סיקסק', en: 'Spur-winged Lapwing', sci: 'Vanellus spinosus', family: 'חופמיים' },
  { he: 'קיווית שחורת-ראש', en: 'Black-headed Lapwing', sci: 'Vanellus tectus', family: 'חופמיים' },
  { he: 'קיווית אדומת-משקפיים', en: '', sci: '', family: '' },
  { he: 'קיווית להקנית', en: 'Sociable Lapwing', sci: 'Vanellus gregarius', family: 'חופמיים' },
  { he: 'קיווית לבנת- זנב', en: 'White-tailed Lapwing', sci: 'Vanellus leucurus', family: 'חופמיים' },
  { he: 'חופזי זהוב', en: 'European Golden Plover', sci: 'Pluvialis apricaria', family: 'חופמיים' },
  { he: 'חופזי קטן', en: 'Pacific Golden Plover', sci: 'Pluvialis fulva', family: 'חופמיים' },
  { he: 'חופזי אמריקני', en: 'American Golden Plover', sci: 'Pluvialis dominica', family: 'חופמיים' },
  { he: 'חופמי מנומר', en: 'Grey Plover', sci: 'Pluvialis squatarola', family: 'חופמיים' },
  { he: 'חופמי צווארון', en: 'Common Ringed Plover', sci: 'Charadrius hiaticula', family: 'חופמיים' },
  { he: 'חופמי גדות', en: 'Little Ringed Plover', sci: 'Charadrius dubius', family: 'חופמיים' },
  { he: 'חופמי אפריקני', en: 'Kittlitz\'s Plover', sci: 'Charadrius pecuarius', family: 'חופמיים' },
  { he: 'חופמי תלת-צווארון', en: 'Three-banded Plover', sci: 'Charadrius tricollaris', family: 'חופמיים' },
  { he: 'חופמי אלכסנדרי', en: 'Kentish Plover', sci: 'Charadrius alexandrinus', family: 'חופמיים' },
  { he: 'חופמי מונגולי', en: 'Lesser Sand Plover', sci: 'Charadrius mongolus', family: 'חופמיים' },
  { he: 'חופמי חוף', en: 'Greater Sand Plover', sci: 'Charadrius leschenaultii', family: 'חופמיים' },
  { he: 'חופמי אסיה', en: 'Caspian Plover', sci: 'Charadrius asiaticus', family: 'חופמיים' },
  { he: 'חופמי ערבה', en: 'Eurasian Dotterel', sci: 'Charadrius morinellus', family: 'חופמיים' },
  { he: 'חרטומית בנגלית', en: 'Greater Painted-snipe', sci: 'Rostratula benghalensis', family: 'מקוריתיים' },
  { he: 'חרמשון קטן', en: 'Eurasian Whimbrel', sci: 'Numenius phaeopus', family: 'חרטומניים' },
  { he: 'חרמשון דק-מקור', en: 'Slender-billed Curlew', sci: 'Numenius tenuirostris', family: 'חרטומניים' },
  { he: 'חרמשון גדול', en: 'Eurasian Curlew', sci: 'Numenius arquata', family: 'חרטומניים' },
  { he: 'לימוזה חומת-בטן', en: 'Bar-tailed Godwit', sci: 'Limosa lapponica', family: 'חרטומניים' },
  { he: 'לימוזה מצויה', en: 'Black-tailed Godwit', sci: 'Limosa limosa', family: 'חרטומניים' },
  { he: 'ארנריה אדמונית', en: 'Ruddy Turnstone', sci: 'Arenaria interpres', family: 'חרטומניים' },
  { he: 'חופית גדולה', en: 'Great Knot', sci: 'Calidris tenuirostris', family: 'חרטומניים' },
  { he: 'חופית להקנית', en: 'Red Knot', sci: 'Calidris canutus', family: 'חרטומניים' },
  { he: 'לוחם', en: 'Ruff', sci: 'Calidris pugnax', family: 'חרטומניים' },
  { he: 'חרמשית', en: 'Broad-billed Sandpiper', sci: 'Calidris falcinellus', family: 'חרטומניים' },
  { he: 'חופית מגלית', en: 'Curlew Sandpiper', sci: 'Calidris ferruginea', family: 'חרטומניים' },
  { he: 'חופית טמינק', en: 'Temminck\'s Stint', sci: 'Calidris temminckii', family: 'חרטומניים' },
  { he: 'חופית לבנת־שת', en: 'White-rumped Sandpiper', sci: 'Calidris fuscicollis', family: 'חרטומניים' },
  { he: 'חופית כהת-חזה', en: 'Pectoral Sandpiper', sci: 'Calidris melanotos', family: 'חרטומניים' },
  { he: 'חופית אמריקנית', en: 'Semipalmated Sandpiper', sci: 'Calidris pusilla', family: 'חרטומניים' },
  { he: 'חופית ארוכת-אצבעות', en: '', sci: '', family: '' },
  { he: 'חופית אדומת צוואר', en: 'Red-necked Stint', sci: 'Calidris ruficollis', family: 'חרטומניים' },
  { he: 'חופית לבנה', en: 'Sanderling', sci: 'Calidris alba', family: 'חרטומניים' },
  { he: 'חופית אלפינית', en: 'Dunlin', sci: 'Calidris alpina', family: 'חרטומניים' },
  { he: 'חופית בירד', en: 'Baird\'s Sandpiper', sci: 'Calidris bairdii', family: 'חרטומניים' },
  { he: 'חופית קטנה', en: 'Little Stint', sci: 'Calidris minuta', family: 'חרטומניים' },
  { he: 'חרטומנית ארוכת-מקור דוביצ\'ר', en: '', sci: '', family: '' },
  { he: 'חרטומן יערות', en: 'Eurasian Woodcock', sci: 'Scolopax rusticola', family: 'חרטומניים' },
  { he: 'חרטומית גמדית', en: 'Jack Snipe', sci: 'Lymnocryptes minimus', family: 'חרטומניים' },
  { he: 'חרטומית חדת-זנב', en: 'Pin-tailed Snipe', sci: 'Gallinago stenura', family: 'חרטומניים' },
  { he: 'חרטומית בינונית', en: 'Great Snipe', sci: 'Gallinago media', family: 'חרטומניים' },
  { he: 'חרטומית ביצות', en: 'Common Snipe', sci: 'Gallinago gallinago', family: 'חרטומניים' },
  { he: 'ביצנית אפורה', en: 'Terek Sandpiper', sci: 'Xenus cinereus', family: 'חרטומניים' },
  { he: 'שחיינית תלת־גונית', en: 'Wilson\'s Phalarope', sci: 'Phalaropus tricolor', family: 'חרטומניים' },
  { he: 'שחיינית צרת-מקור', en: 'Red-necked Phalarope', sci: 'Phalaropus lobatus', family: 'חרטומניים' },
  { he: 'שחיינית רחבת-מקור', en: 'Red Phalarope', sci: 'Phalaropus fulicarius', family: 'חרטומניים' },
  { he: 'ביצנית לבנת בטן', en: 'Common Sandpiper', sci: 'Actitis hypoleucos', family: 'חרטומניים' },
  { he: 'ביצנית שחורת כנף', en: 'Green Sandpiper', sci: 'Tringa ochropus', family: 'חרטומניים' },
  { he: 'ביצנית צהובת-רגל', en: 'Lesser Yellowlegs', sci: 'Tringa flavipes', family: 'חרטומניים' },
  { he: 'ביצנית לבנת-כנף', en: 'Common Redshank', sci: 'Tringa totanus', family: 'חרטומניים' },
  { he: 'ביצנית עדינה', en: 'Marsh Sandpiper', sci: 'Tringa stagnatilis', family: 'חרטומניים' },
  { he: 'ביצנית מנומרת', en: 'Wood Sandpiper', sci: 'Tringa glareola', family: 'חרטומניים' },
  { he: 'ביצנית אדומת רגל', en: 'Spotted Redshank', sci: 'Tringa erythropus', family: 'חרטומניים' },
  { he: 'ביצנית ירוקת רגל', en: 'Common Greenshank', sci: 'Tringa nebularia', family: 'חרטומניים' },
  { he: 'דרומס', en: 'Crab-plover', sci: 'Dromas ardeola', family: 'דרומסיים' },
  { he: 'רץ מדבר', en: 'Cream-colored Courser', sci: 'Cursorius cursor', family: 'שדמתיים' },
  { he: 'שדמית אדומת-כנף', en: 'Collared Pratincole', sci: 'Glareola pratincola', family: 'שדמתיים' },
  { he: 'שדמית מזרחית', en: 'Oriental Pratincole', sci: 'Glareola maldivarum', family: 'שדמתיים' },
  { he: 'שדמית שחורת כנף', en: 'Black-winged Pratincole', sci: 'Glareola nordmanni', family: 'שדמתיים' },
  { he: 'גיזרן אפריקני', en: 'African Skimmer', sci: 'Rynchops flavirostris', family: 'שחפיים' },
  { he: 'ריסה שחורת-רגל', en: 'Black-legged Kittiwake', sci: 'Rissa tridactyla', family: 'שחפיים' },
  { he: 'שחף קדוד-זנב', en: 'Sabine\'s Gull', sci: 'Xema sabini', family: 'שחפיים' },
  { he: 'שחף צר-מקור', en: 'Slender-billed Gull', sci: 'Chroicocephalus genei', family: 'שחפיים' },
  { he: 'שחף חום-ראש', en: 'Brown-headed Gull', sci: 'Chroicocephalus brunnicephalus', family: 'שחפיים' },
  { he: 'שחף אגמים', en: 'Black-headed Gull', sci: 'Chroicocephalus ridibundus', family: 'שחפיים' },
  { he: 'שחף אפור-ראש', en: 'Grey-headed Gull', sci: 'Chroicocephalus cirrocephalus', family: 'שחפיים' },
  { he: 'שחף גמדי', en: 'Little Gull', sci: 'Hydrocoloeus minutus', family: 'שחפיים' },
  { he: 'שחף אפור זנב', en: 'Franklin\'s Gull', sci: 'Leucophaeus pipixcan', family: 'שחפיים' },
  { he: 'שחף אדום-מקור', en: 'Audouin\'s Gull', sci: 'Ichthyaetus audouinii', family: 'שחפיים' },
  { he: 'שחף שחור-ראש', en: 'Mediterranean Gull', sci: 'Ichthyaetus melanocephalus', family: 'שחפיים' },
  { he: 'שחף עיטי', en: 'Pallas\'s Gull', sci: 'Ichthyaetus ichthyaetus', family: 'שחפיים' },
  { he: 'שחף לבן-עין', en: 'White-eyed Gull', sci: 'Ichthyaetus leucophthalmus', family: 'שחפיים' },
  { he: 'שחף כהה', en: 'Sooty Gull', sci: 'Ichthyaetus hemprichii', family: 'שחפיים' },
  { he: 'שחף אפרורי', en: 'Common Gull', sci: 'Larus canus', family: 'שחפיים' },
  { he: 'שחף ימי', en: 'Great Black-backed Gull', sci: 'Larus marinus', family: 'שחפיים' },
  { he: 'שחף לבן-כנף', en: 'Glaucous Gull', sci: 'Larus hyperboreus', family: 'שחפיים' },
  { he: 'שחף כספי', en: 'European Herring Gull', sci: 'Larus argentatus', family: 'שחפיים' },
  { he: 'שחף צהוב רגל כספי', en: 'Caspian Gull', sci: 'Larus cachinnans', family: 'שחפיים' },
  { he: 'שחף צהוב-רגל ים תיכוני', en: '', sci: '', family: '' },
  { he: 'שחף ארמני', en: 'Armenian Gull', sci: 'Larus armenicus', family: 'שחפיים' },
  { he: 'שחף שחור', en: 'Lesser Black-backed Gull', sci: 'Larus fuscus', family: 'שחפיים' },
  { he: 'שחפית עבת מקור', en: 'Gull-billed Tern', sci: 'Gelochelidon nilotica', family: 'שחפיים' },
  { he: 'שחפית כספית', en: 'Caspian Tern', sci: 'Hydroprogne caspia', family: 'שחפיים' },
  { he: 'שחפית צהובת־מקור', en: 'Greater Crested Tern', sci: 'Thalasseus bergii', family: 'שחפיים' },
  { he: 'שחפית בנגלית', en: 'Lesser Crested Tern', sci: 'Thalasseus bengalensis', family: 'שחפיים' },
  { he: 'שחפית שחורת-מקור', en: '', sci: '', family: '' },
  { he: 'שחפית גמדית', en: 'Little Tern', sci: 'Sternula albifrons', family: 'שחפיים' },
  { he: 'שחפית סוונדרס', en: 'Saunders\'s Tern', sci: 'Sternula saundersi', family: 'שחפיים' },
  { he: 'שחפית רסן', en: 'Bridled Tern', sci: 'Onychoprion anaethetus', family: 'שחפיים' },
  { he: 'שחפית כהה', en: 'Sooty Tern', sci: 'Onychoprion fuscatus', family: 'שחפיים' },
  { he: 'שחפית ורדרדת', en: 'Roseate Tern', sci: 'Sterna dougallii', family: 'שחפיים' },
  { he: 'שחפית ים', en: 'Common Tern', sci: 'Sterna hirundo', family: 'שחפיים' },
  { he: 'שחפית שוניות', en: 'White-cheeked Tern', sci: 'Sterna repressa', family: 'שחפיים' },
  { he: 'שחפית הקוטב', en: 'Arctic Tern', sci: 'Sterna paradisaea', family: 'שחפיים' },
  { he: 'מרומית לבנת לחי', en: 'Whiskered Tern', sci: 'Chlidonias hybrida', family: 'שחפיים' },
  { he: 'מרומית לבנת כנף', en: 'White-winged Tern', sci: 'Chlidonias leucopterus', family: 'שחפיים' },
  { he: 'מרומית שחורה', en: 'Black Tern', sci: 'Chlidonias niger', family: 'שחפיים' },
  { he: 'חמסן דרומי', en: 'South Polar Skua', sci: 'Stercorarius maccormicki', family: 'חמסניים' },
  { he: 'חמסן גדול', en: 'Great Skua', sci: 'Stercorarius skua', family: 'חמסניים' },
  { he: 'חמסן רחב-אברה', en: 'Pomarine Jaeger', sci: 'Stercorarius pomarinus', family: 'חמסניים' },
  { he: 'חמסן טפיל', en: 'Parasitic Jaeger', sci: 'Stercorarius parasiticus', family: 'חמסניים' },
  { he: 'חמסן זנבתן', en: 'Long-tailed Jaeger', sci: 'Stercorarius longicaudus', family: 'חמסניים' },
  { he: 'פיתון ים-סוף', en: 'Red-billed Tropicbird', sci: 'Phaethon aethereus', family: 'פתוניים' },
  { he: 'צוללן אדום-גרון', en: 'Red-throated Loon', sci: 'Gavia stellata', family: 'צוללניים' },
  { he: 'צוללן שחור-גרון', en: 'Black-throated Loon', sci: 'Gavia arctica', family: 'צוללניים' },
  { he: 'יסעורון וילסון', en: 'Wilson\'s Storm Petrel', sci: 'םיימורד םיינורועסי', family: '' },
  { he: 'אלבטרוס לבן-כיפה', en: 'Shy Albatross', sci: 'Thalassarche cauta', family: 'אלבטרוסיים' },
  { he: 'יסעורון קטן', en: 'European Storm Petrel', sci: 'םיינופצ םיינורועסי', family: '' },
  { he: 'יסעורון פסיפי', en: 'Swinhoe\'s Storm Petrel', sci: 'םיינופצ םיינורועסי', family: '' },
  { he: 'יסעורון אטלנטי', en: 'Leach\'s Storm Petrel', sci: 'םיינופצ םיינורועסי', family: '' },
  { he: 'יסעורון מדירה', en: 'Band-rumped Storm Petrel', sci: 'םיינופצ םיינורועסי', family: '' },
  { he: 'סערון אטלנטי', en: 'Atlantic Petrel', sci: 'Pterodroma incerta', family: 'יסעוריים' },
  { he: 'סערון קטיפתי', en: 'Soft-plumaged Petrel', sci: 'Pterodroma mollis', family: 'יסעוריים' },
  { he: 'סערון לבן-חזה', en: 'Fea\'s Petrel', sci: 'Pterodroma feae', family: 'יסעוריים' },
  { he: 'יסעור לבן-מצח', en: 'Streaked Shearwater', sci: 'Calonectris leucomelas', family: 'יסעוריים' },
  { he: 'יסעור גדול', en: 'Scopoli\'s Shearwater', sci: 'Calonectris diomedea', family: 'יסעוריים' },
  { he: 'יסעור כהה', en: 'Sooty Shearwater', sci: 'Ardenna grisea', family: 'יסעוריים' },
  { he: 'יסעור כהה-כנף', en: 'Flesh-footed Shearwater', sci: 'Ardenna carneipes', family: 'יסעוריים' },
  { he: 'יסעור שחור-כיפה', en: 'Great Shearwater', sci: 'Ardenna gravis', family: 'יסעוריים' },
  { he: 'יסעור מצוי', en: 'Yelkouan Shearwater', sci: 'Puffinus yelkouan', family: 'יסעוריים' },
  { he: 'יסעור מערבי בלרי', en: 'Balearic Shearwater', sci: 'Puffinus mauretanicus', family: 'יסעוריים' },
  { he: 'יסעור פרסי', en: 'Persian Shearwater', sci: 'Puffinus persicus', family: 'יסעוריים' },
  { he: 'יסעור טרופי', en: 'Tropical Shearwater', sci: 'Puffinus bailloni', family: 'יסעוריים' },
  { he: 'יסעור קטן', en: 'Little Shearwater', sci: 'Puffinus assimilis', family: 'יסעוריים' },
  { he: 'יסעור בארלו', en: 'Barolo Shearwater', sci: 'Puffinus baroli', family: 'יסעוריים' },
  { he: 'סערונית כהה', en: 'Bulwer\'s Petrel', sci: 'Bulweria bulwerii', family: 'יסעוריים' },
  { he: 'חסידן ורוד', en: 'Yellow-billed Stork', sci: 'Mycteria ibis', family: 'חסידתיים' },
  { he: 'חסידה שחורה', en: 'Black Stork', sci: 'Ciconia nigra', family: 'חסידתיים' },
  { he: 'חסידה לבנה', en: 'White Stork', sci: 'Ciconia ciconia', family: 'חסידתיים' },
  { he: 'מרבו', en: 'Marabou Stork', sci: 'Leptoptilos crumenifer', family: 'חסידתיים' },
  { he: 'פריגט קטן', en: 'Lesser Frigatebird', sci: 'Fregata ariel', family: 'פרגטיים' },
  { he: 'סולה צפונית', en: 'Northern Gannet', sci: 'Morus bassanus', family: 'סולתיים' },
  { he: 'סולת המסיכה', en: 'Masked Booby', sci: 'Sula dactylatra', family: 'סולתיים' },
  { he: 'סולה לבנת-בטן', en: 'Brown Booby', sci: 'Sula leucogaster', family: 'סולתיים' },
  { he: 'נחשון אפריקני', en: 'African Darter', sci: 'Anhinga rufa', family: 'נחשוניים' },
  { he: 'קורמורן גמדי', en: 'Pygmy Cormorant', sci: 'Microcarbo pygmaeus', family: 'קורמורניים' },
  { he: 'קורמורן גדול', en: 'Great Cormorant', sci: 'Phalacrocorax carbo', family: 'קורמורניים' },
  { he: 'קורמורן ימי', en: 'European Shag', sci: 'Gulosus aristotelis', family: 'קורמורניים' },
  { he: 'מגלן מצויץ', en: 'Northern Bald Ibis', sci: 'םינלגמ , םיינפכ', family: '' },
  { he: 'מגלן חום', en: 'Glossy Ibis', sci: 'םינלגמ , םיינפכ', family: '' },
  { he: 'כפן', en: 'Eurasian Spoonbill', sci: 'םינלגמ , םיינפכ', family: '' },
  { he: 'אנפה מסורטטת', en: 'Eurasian Bittern', sci: 'Botaurus stellaris', family: 'אנפתיים' },
  { he: 'אנפית גמדית', en: 'Little Bittern', sci: 'Ixobrychus minutus', family: 'אנפתיים' },
  { he: 'אנפת לילה', en: 'Black-crowned Night Heron', sci: 'Nycticorax nycticorax', family: 'אנפתיים' },
  { he: 'אנפית מנגרובים', en: 'Striated Heron', sci: 'Butorides striata', family: 'אנפתיים' },
  { he: 'אנפית סוף', en: 'Squacco Heron', sci: 'Ardeola ralloides', family: 'אנפתיים' },
  { he: 'אנפית אגמים סינית/ אנפית בכחוס', en: '', sci: '', family: '' },
  { he: 'אנפית בקר', en: 'Western Cattle Egret', sci: 'Bubulcus ibis', family: 'אנפתיים' },
  { he: 'אנפה אפורה', en: 'Grey Heron', sci: 'Ardea cinerea', family: 'אנפתיים' },
  { he: 'אנפה שחורת-ראש', en: 'Black-headed Heron', sci: 'Ardea melanocephala', family: 'אנפתיים' },
  { he: 'אנפת גוליית', en: 'Goliath Heron', sci: 'Ardea goliath', family: 'אנפתיים' },
  { he: 'אנפה ארגמנית', en: 'Purple Heron', sci: 'Ardea purpurea', family: 'אנפתיים' },
  { he: 'לבנית גדולה', en: 'Great Egret', sci: 'Ardea alba', family: 'אנפתיים' },
  { he: 'לבנית בינונית', en: 'Intermediate Egret', sci: 'Ardea intermedia', family: 'אנפתיים' },
  { he: 'אנפה שחורה', en: 'Black Heron', sci: 'Egretta ardesiaca', family: 'אנפתיים' },
  { he: 'לבנית קטנה', en: 'Little Egret', sci: 'Egretta garzetta', family: 'אנפתיים' },
  { he: 'לבנית ים-סוף', en: 'Western Reef Heron', sci: 'Egretta gularis', family: 'אנפתיים' },
  { he: 'שקנאי מצוי', en: 'Great White Pelican', sci: 'Pelecanus onocrotalus', family: 'שקנאיים' },
  { he: 'שקנאי קטן', en: 'Pink-backed Pelican', sci: 'Pelecanus rufescens', family: 'שקנאיים' },
  { he: 'שקנאי מסולסל', en: 'Dalmatian Pelican', sci: 'Pelecanus crispus', family: 'שקנאיים' },
  { he: 'שלך', en: 'Western Osprey', sci: 'Pandion haliaetus', family: 'שלכיים' },
  { he: 'דאה שחורת-כתף', en: 'Black-winged Kite', sci: 'Elanus caeruleus', family: 'נציים' },
  { he: 'פרס', en: 'Bearded Vulture', sci: 'Gypaetus barbatus', family: 'נציים' },
  { he: 'רחם מדברי', en: 'Egyptian Vulture', sci: 'Neophron percnopterus', family: 'נציים' },
  { he: 'איית צרעים', en: 'European Honey Buzzard', sci: 'Pernis apivorus', family: 'נציים' },
  { he: 'איה מצויצת )מזרחית(', en: '', sci: '', family: '' },
  { he: 'נשר אפריקני', en: 'White-backed Vulture', sci: 'Gyps africanus', family: 'נציים' },
  { he: 'נשר דרומי-רופל', en: 'Rüppell\'s Vulture', sci: 'Gyps rueppelli', family: 'נציים' },
  { he: 'נשר מקראי', en: 'Griffon Vulture', sci: 'Gyps fulvus', family: 'נציים' },
  { he: 'עוזנייה שחורה', en: 'Cinereous Vulture', sci: 'Aegypius monachus', family: 'נציים' },
  { he: 'עוזניית הנגב', en: 'Lappet-faced Vulture', sci: 'Torgos tracheliotos', family: 'נציים' },
  { he: 'חיוויאי הנחשים', en: 'Short-toed Snake Eagle', sci: 'Circaetus gallicus', family: 'נציים' },
  { he: 'חיוויאי להטוטן', en: 'Bateleur', sci: 'Terathopius ecaudatus', family: 'נציים' },
  { he: 'עיט חורש', en: 'Lesser Spotted Eagle', sci: 'Clanga pomarina', family: 'נציים' },
  { he: 'עיט צפרדעים', en: 'Greater Spotted Eagle', sci: 'Clanga clanga', family: 'נציים' },
  { he: 'עיט גמדי', en: 'Booted Eagle', sci: 'Hieraaetus pennatus', family: 'נציים' },
  { he: 'עיט סוואנות', en: 'Tawny Eagle', sci: 'Aquila rapax', family: 'נציים' },
  { he: 'עיט ערבות', en: 'Steppe Eagle', sci: 'Aquila nipalensis', family: 'נציים' },
  { he: 'עיט שמש', en: 'Eastern Imperial Eagle', sci: 'Aquila heliaca', family: 'נציים' },
  { he: 'עיט זהוב', en: 'Golden Eagle', sci: 'Aquila chrysaetos', family: 'נציים' },
  { he: 'עיט שחור', en: 'Verreaux\'s Eagle', sci: 'Aquila verreauxii', family: 'נציים' },
  { he: 'עיט ניצי', en: 'Bonelli\'s Eagle', sci: 'Aquila fasciata', family: 'נציים' },
  { he: 'נץ קולני אפור', en: 'Dark Chanting Goshawk', sci: 'Melierax metabates', family: 'נציים' },
  { he: 'נץ אפור מזרחי', en: 'Eastern Chanting Goshawk', sci: 'Melierax poliopterus', family: 'נציים' },
  { he: 'נץ הים הכספי', en: 'Shikra', sci: 'Accipiter badius', family: 'נציים' },
  { he: 'נץ קצר- אצבעות', en: 'Levant Sparrowhawk', sci: 'Accipiter brevipes', family: 'נציים' },
  { he: 'נץ מצוי', en: 'Eurasian Sparrowhawk', sci: 'Accipiter nisus', family: 'נציים' },
  { he: 'נץ גדול', en: 'Northern Goshawk', sci: 'Accipiter gentilis', family: 'נציים' },
  { he: 'זרון סוף', en: 'Western Marsh Harrier', sci: 'Circus aeruginosus', family: 'נציים' },
  { he: 'זרון תכול', en: 'Hen Harrier', sci: 'Circus cyaneus', family: 'נציים' },
  { he: 'זרון שדות', en: 'Pallid Harrier', sci: 'Circus macrourus', family: 'נציים' },
  { he: 'זרון פס', en: 'Montagu\'s Harrier', sci: 'Circus pygargus', family: 'נציים' },
  { he: 'דיה אדומה', en: 'Red Kite', sci: 'Milvus milvus', family: 'נציים' },
  { he: 'דיה שחורה', en: 'Black Kite', sci: 'Milvus migrans', family: 'נציים' },
  { he: 'דיה צהובת-מקור', en: 'Yellow-billed Kite', sci: 'Milvus aegyptius', family: 'נציים' },
  { he: 'עיטם לבן-זנב', en: 'White-tailed Eagle', sci: 'Haliaeetus albicilla', family: 'נציים' },
  { he: 'עקב מכנסיים', en: 'Rough-legged Buzzard', sci: 'Buteo lagopus', family: 'נציים' },
  { he: 'עקב עיטי', en: 'Long-legged Buzzard', sci: 'Buteo rufinus', family: 'נציים' },
  { he: 'עקב חורף', en: 'Common Buzzard', sci: 'Buteo buteo', family: 'נציים' },
  { he: 'תנשמת לבנה', en: 'Western Barn Owl', sci: 'Tyto alba', family: 'תנשמתיים' },
  { he: 'כוס החרבות', en: 'Little Owl', sci: 'Athene noctua', family: 'ינשופיים' },
  { he: 'שעיר מצוי', en: 'Eurasian Scops Owl', sci: 'Otus scops', family: 'ינשופיים' },
  { he: 'שעיר משורטט', en: 'Pallid Scops Owl', sci: 'Otus brucei', family: 'ינשופיים' },
  { he: 'ינשוף עצים', en: 'Long-eared Owl', sci: 'Asio otus', family: 'ינשופיים' },
  { he: 'ינשוף שדות', en: 'Short-eared Owl', sci: 'Asio flammeus', family: 'ינשופיים' },
  { he: 'אוח עיטי', en: 'Eurasian Eagle-Owl', sci: 'Bubo bubo', family: 'ינשופיים' },
  { he: 'אוח מדברי', en: 'Pharaoh Eagle-Owl', sci: 'Bubo ascalaphus', family: 'ינשופיים' },
  { he: 'קטופה', en: 'Brown Fish Owl', sci: 'Ketupa zeylonensis', family: 'ינשופיים' },
  { he: 'לילית מצויה', en: 'Tawny Owl', sci: 'Strix aluco', family: 'ינשופיים' },
  { he: 'לילית מדבר הדורמית', en: '', sci: '', family: '' },
  { he: 'דוכיפת', en: 'Eurasian Hoopoe', sci: 'Upupa epops', family: 'דוכיפתיים' },
  { he: 'כחל מצוי', en: 'European Roller', sci: 'Coracias garrulus', family: 'כחליים' },
  { he: 'כחל צהוב מקור', en: 'Broad-billed Roller', sci: 'Eurystomus glaucurus', family: 'כחליים' },
  { he: 'שלדג לבן חזה', en: 'White-throated Kingfisher', sci: 'Halcyon smyrnensis', family: 'שלדגיים' },
  { he: 'שלדג גמדי', en: 'Common Kingfisher', sci: 'Alcedo atthis', family: 'שלדגיים' },
  { he: 'פרפור עקוד', en: 'Pied Kingfisher', sci: 'Ceryle rudis', family: 'שלדגיים' },
  { he: 'שרקרק לבן-גרון', en: 'White-throated Bee-eater', sci: 'Merops albicollis', family: 'שרקרקיים' },
  { he: 'שרקרק גמדי', en: 'Asian Green Bee-eater', sci: 'Merops orientalis', family: 'שרקרקיים' },
  { he: 'שרקרק ירוק', en: 'Blue-cheeked Bee-eater', sci: 'Merops persicus', family: 'שרקרקיים' },
  { he: 'שרקרק מצוי', en: 'European Bee-eater', sci: 'Merops apiaster', family: 'שרקרקיים' },
  { he: 'סבראש', en: 'Eurasian Wryneck', sci: 'Jynx torquilla', family: 'נקריים' },
  { he: 'נקר סורי', en: 'Syrian Woodpecker', sci: 'Dendrocopos syriacus', family: 'נקריים' },
  { he: 'בז אדום', en: 'Lesser Kestrel', sci: 'Falco naumanni', family: 'בזיים' },
  { he: 'בז מצוי', en: 'Common Kestrel', sci: 'Falco tinnunculus', family: 'בזיים' },
  { he: 'בז ערב', en: 'Red-footed Falcon', sci: 'Falco vespertinus', family: 'בזיים' },
  { he: 'בז חופים', en: 'Eleonora\'s Falcon', sci: 'Falco eleonorae', family: 'בזיים' },
  { he: 'בז שחור', en: 'Sooty Falcon', sci: 'Falco concolor', family: 'בזיים' },
  { he: 'בז גמדי', en: 'Merlin', sci: 'Falco columbarius', family: 'בזיים' },
  { he: 'בז עצים', en: 'Eurasian Hobby', sci: 'Falco subbuteo', family: 'בזיים' },
  { he: 'בז צוקים', en: 'Lanner Falcon', sci: 'Falco biarmicus', family: 'בזיים' },
  { he: 'בז ציידים', en: 'Saker Falcon', sci: 'Falco cherrug', family: 'בזיים' },
  { he: 'בז נודד', en: 'Peregrine Falcon', sci: 'Falco peregrinus', family: 'בזיים' },
  { he: 'תוכי נזירי', en: 'Monk Parakeet', sci: 'Myiopsitta monachus', family: 'תוכיים' },
  { he: 'דררה אלכסנדרונית', en: 'Alexandrine Parakeet', sci: 'Psittacula eupatria', family: 'דרראים' },
  { he: 'דררה מצויה', en: 'Rose-ringed Parakeet', sci: 'Psittacula krameri', family: 'דרראים' },
  { he: 'פרסונטה', en: 'Yellow-collared Lovebird', sci: 'Agapornis personatus', family: 'דרראים' },
  { he: 'חנקן אדום גב', en: 'Red-backed Shrike', sci: 'Lanius collurio', family: 'חנקניים' },
  { he: 'חנקן ערבות', en: 'Isabelline Shrike', sci: 'Lanius isabellinus', family: 'חנקניים' },
  { he: 'חנקן אדום זנב. טורקיסטאני', en: '', sci: '', family: '' },
  { he: 'חנקן זנבתן', en: 'Long-tailed Shrike', sci: 'Lanius schach', family: 'חנקניים' },
  { he: 'חנקן שחור-מצח', en: 'Lesser Grey Shrike', sci: 'Lanius minor', family: 'חנקניים' },
  { he: 'חנקן גדול', en: 'Great Grey Shrike', sci: 'Lanius excubitor', family: 'חנקניים' },
  { he: 'חנקן גדול דרומי', en: 'Iberian Grey Shrike', sci: 'Lanius meridionalis', family: 'חנקניים' },
  { he: 'חנקן אדום ראש', en: 'Woodchat Shrike', sci: 'Lanius senator', family: 'חנקניים' },
  { he: 'חנקן נובי', en: 'Masked Shrike', sci: 'Lanius nubicus', family: 'חנקניים' },
  { he: 'זהבן מחלל', en: 'Eurasian Golden Oriole', sci: 'Oriolus oriolus', family: 'זהבניים' },
  { he: 'דרונגו אפרורי', en: 'Ashy Drongo', sci: 'Dicrurus leucophaeus', family: 'דרונגים' },
  { he: 'עורבני שחור-כיפה', en: 'Eurasian Jay', sci: 'Garrulus glandarius', family: 'עורביים' },
  { he: 'זג אדום-מקור', en: 'Red-billed Chough', sci: 'Pyrrhocorax pyrrhocorax', family: 'עורביים' },
  { he: 'זג צהוב-מקור', en: 'Alpine Chough', sci: 'Pyrrhocorax graculus', family: 'עורביים' },
  { he: 'קאק', en: 'Western Jackdaw', sci: 'Coloeus monedula', family: 'עורביים' },
  { he: 'עורב מזרע', en: 'Rook', sci: 'Corvus frugilegus', family: 'עורביים' },
  { he: 'עורב אפור', en: 'Hooded Crow', sci: 'Corvus cornix', family: 'עורביים' },
  { he: 'עורב חום עורף', en: 'Brown-necked Raven', sci: 'Corvus ruficollis', family: 'עורביים' },
  { he: 'עורב שחור', en: 'Northern Raven', sci: 'Corvus corax', family: 'עורביים' },
  { he: 'עורב קצר זנב', en: 'Fan-tailed Raven', sci: 'Corvus rhipidurus', family: 'עורביים' },
  { he: 'עורב הודי', en: 'House Crow', sci: 'Corvus splendens', family: 'עורביים' },
  { he: 'עורב הכף', en: 'Cape Crow', sci: 'Corvus capensis', family: 'עורביים' },
  { he: 'ציצנית', en: 'Bohemian Waxwing', sci: 'Bombycilla garrulus', family: 'ציצניתיים' },
  { he: 'חיוורנית אפורה', en: 'Grey Hypocolius', sci: 'Hypocolius ampelinus', family: 'חיוורניתיים' },
  { he: 'ירגזי שחור', en: 'Coal Tit', sci: 'Periparus ater', family: 'ירגזיים' },
  { he: 'ירגזי חרמון', en: 'Sombre Tit', sci: 'Poecile lugubris', family: 'ירגזיים' },
  { he: 'ירגזי כחול', en: 'Eurasian Blue Tit', sci: 'Cyanistes caeruleus', family: 'ירגזיים' },
  { he: 'ירגזי מצוי', en: 'Great Tit', sci: 'Parus major', family: 'ירגזיים' },
  { he: 'רמית', en: 'Eurasian Penduline Tit', sci: 'Remiz pendulinus', family: 'רמיזיים' },
  { he: 'שפמתן', en: 'Bearded Reedling', sci: 'Panurus biarmicus', family: 'שפמתניים' },
  { he: 'אלימון', en: 'Greater Hoopoe-Lark', sci: 'Alaemon alaudipes', family: 'עפרוניים' },
  { he: 'עפרוני עב מקור', en: 'Thick-billed Lark', sci: 'Ramphocoris clotbey', family: 'עפרוניים' },
  { he: 'עפרוני מדבר', en: 'Desert Lark', sci: 'Ammomanes deserti', family: 'עפרוניים' },
  { he: 'עפרוני חכלילי', en: 'Bar-tailed Lark', sci: 'Ammomanes cinctura', family: 'עפרוניים' },
  { he: 'צחיחן שחור-כיפה', en: 'Black-crowned Sparrow-Lark', sci: 'Eremopterix nigriceps', family: 'עפרוניים' },
  { he: 'צחיחן חום-כיפה', en: 'Chestnut-headed Sparrow-Lark', sci: 'Eremopterix signatus', family: 'עפרוניים' },
  { he: 'חוגת עצים', en: 'Woodlark', sci: 'Lullula arborea', family: 'עפרוניים' },
  { he: 'זרעית קטנה', en: 'Oriental Skylark', sci: 'Alauda gulgula', family: 'עפרוניים' },
  { he: 'זרעית השדה', en: 'Eurasian Skylark', sci: 'Alauda arvensis', family: 'עפרוניים' },
  { he: 'עפרוני מצוייץ', en: 'Crested Lark', sci: 'Galerida cristata', family: 'עפרוניים' },
  { he: 'צחיחנית החרמון', en: 'Horned Lark', sci: 'Eremophila alpestris', family: 'עפרוניים' },
  { he: 'צחיחנית המדבר', en: 'Temminck\'s Lark', sci: 'Eremophila bilopha', family: 'עפרוניים' },
  { he: 'עפרונן קצר-אצבעות טיביטי', en: '', sci: '', family: '' },
  { he: 'עפרונן קצר אצבעות', en: 'Greater Short-toed Lark', sci: 'Calandrella brachydactyla', family: 'עפרוניים' },
  { he: 'עפרוני פסגות', en: 'Bimaculated Lark', sci: 'Melanocorypha bimaculata', family: 'עפרוניים' },
  { he: 'עפרוני ענק', en: 'Calandra Lark', sci: 'Melanocorypha calandra', family: 'עפרוניים' },
  { he: 'עפרוני שחור-זנב', en: 'Dunn\'s Lark', sci: 'Eremalauda dunni', family: 'עפרוניים' },
  { he: 'עפרונן גמדי', en: 'Mediterranean Short-toed Lark', sci: 'Alaudala rufescens', family: 'עפרוניים' },
  { he: 'בולבול לבן-לחיים', en: 'White-eared Bulbul', sci: 'Pycnonotus leucotis', family: 'בולבוליים' },
  { he: 'בולבול צהוב-שת', en: 'White-spectacled Bulbul', sci: 'Pycnonotus xanthopygos', family: 'בולבוליים' },
  { he: 'כוכית גדות', en: 'Sand Martin', sci: 'Riparia riparia', family: 'סנוניתיים' },
  { he: 'כוכית כהת-גרון', en: 'Brown-throated Martin', sci: 'Riparia paludicola', family: 'סנוניתיים' },
  { he: 'כוכית אפורת-גרון', en: 'Grey-throated Martin', sci: 'Riparia chinensis', family: 'סנוניתיים' },
  { he: 'סנונית סלעים', en: 'Eurasian Crag Martin', sci: 'Ptyonoprogne rupestris', family: 'סנוניתיים' },
  { he: 'סנונית מדבר', en: 'Rock Martin', sci: 'Ptyonoprogne fuligula', family: 'סנוניתיים' },
  { he: 'סנונית רפתות', en: 'Barn Swallow', sci: 'Hirundo rustica', family: 'סנוניתיים' },
  { he: 'סנונית אתיופית', en: 'Ethiopian Swallow', sci: 'Hirundo aethiopica', family: 'סנוניתיים' },
  { he: 'טסית בתים', en: 'Common House Martin', sci: 'Delichon urbicum', family: 'סנוניתיים' },
  { he: 'סנונית מערות', en: 'Red-rumped Swallow', sci: 'Cecropis daurica', family: 'סנוניתיים' },
  { he: 'צטיה חלודית', en: 'Cetti\'s Warbler', sci: 'Cettia cetti', family: 'צ\'טיות' },
  { he: 'מדברון', en: 'Streaked Scrub Warbler', sci: 'Scotocerca inquieta', family: 'מדברוניים' },
  { he: 'עלווית ירוקה', en: 'Wood Warbler', sci: 'Phylloscopus sibilatrix', family: 'סבכיי עַ לְוָוה' },
  { he: 'עלווית לבנת-בטן', en: 'Eastern Bonelli\'s Warbler', sci: 'Phylloscopus orientalis', family: 'סבכיי עַ לְוָוה' },
  { he: 'עלווית לבנת-גבות', en: 'Hume\'s Leaf Warbler', sci: 'Phylloscopus humei', family: 'סבכיי עַ לְוָוה' },
  { he: 'עלווית צהובת גבות', en: 'Yellow-browed Warbler', sci: 'Phylloscopus inornatus', family: 'סבכיי עַ לְוָוה' },
  { he: 'עלווית חורף', en: 'Common Chiffchaff', sci: 'Phylloscopus collybita', family: 'סבכיי עַ לְוָוה' },
  { he: 'עלווית הרים', en: 'Green Warbler', sci: 'Phylloscopus nitidus', family: 'סבכיי עַ לְוָוה' },
  { he: 'עלווית צפונית', en: 'Arctic Warbler', sci: 'Phylloscopus borealis', family: 'סבכיי עַ לְוָוה' },
  { he: 'עלווית מלכילונית', en: 'Pallas\'s Leaf Warbler', sci: 'Phylloscopus proregulus', family: 'סבכיי עַ לְוָוה' },
  { he: 'עלווית עבת מקור', en: 'Radde\'s Warbler', sci: 'Phylloscopus schwarzi', family: 'סבכיי עַ לְוָוה' },
  { he: 'עלווית כהה', en: 'Dusky Warbler', sci: 'Phylloscopus fuscatus', family: 'סבכיי עַ לְוָוה' },
  { he: 'עלווית הודית', en: 'Plain Leaf Warbler', sci: 'Phylloscopus neglectus', family: 'סבכיי עַ לְוָוה' },
  { he: 'עלווית אפורה', en: 'Willow Warbler', sci: 'Phylloscopus trochilus', family: 'סבכיי עַ לְוָוה' },
  { he: 'עלווית קווקאזית', en: 'Mountain Chiffchaff', sci: 'Phylloscopus sindianus', family: 'סבכיי עַ לְוָוה' },
  { he: 'קנית בצרה', en: 'Basra Reed Warbler', sci: 'Acrocephalus griseldis', family: 'סבכיי קנים' },
  { he: 'קנית אירופית', en: 'Great Reed Warbler', sci: 'Acrocephalus arundinaceus', family: 'סבכיי קנים' },
  { he: 'קנית מזרחית', en: 'Oriental Reed Warbler', sci: 'Acrocephalus orientalis', family: 'סבכיי קנים' },
  { he: 'קנית אפריקנית', en: 'Clamorous Reed Warbler', sci: 'Acrocephalus stentoreus', family: 'סבכיי קנים' },
  { he: 'זמירון', en: 'Moustached Warbler', sci: 'Acrocephalus melanopogon', family: 'סבכיי קנים' },
  { he: 'קנית פסים', en: 'Sedge Warbler', sci: 'Acrocephalus schoenobaenus', family: 'סבכיי קנים' },
  { he: 'קנית אורז', en: 'Paddyfield Warbler', sci: 'Acrocephalus agricola', family: 'סבכיי קנים' },
  { he: 'קנית פינית', en: 'Blyth\'s Reed Warbler', sci: 'Acrocephalus dumetorum', family: 'סבכיי קנים' },
  { he: 'קנית קטנה', en: 'Eurasian Reed Warbler', sci: 'Acrocephalus scirpaceus', family: 'סבכיי קנים' },
  { he: 'קנית ביצות', en: 'Marsh Warbler', sci: 'Acrocephalus palustris', family: 'סבכיי קנים' },
  { he: 'שיחנית גמדית', en: 'Booted Warbler', sci: 'Iduna caligata', family: 'סבכיי קנים' },
  { he: 'שיחנית אסייתית', en: 'Sykes\'s Warbler', sci: 'Iduna rama', family: 'סבכיי קנים' },
  { he: 'שיחנית קטנה', en: 'Eastern Olivaceous Warbler', sci: 'Iduna pallida', family: 'סבכיי קנים' },
  { he: 'שיחנית גדולה', en: 'Upcher\'s Warbler', sci: 'Hippolais languida', family: 'סבכיי קנים' },
  { he: 'שיחנית זית', en: 'Olive-tree Warbler', sci: 'Hippolais olivetorum', family: 'סבכיי קנים' },
  { he: 'שיחנית צהובת בטן', en: 'Icterine Warbler', sci: 'Hippolais icterina', family: 'סבכיי קנים' },
  { he: 'חרגולן סיבירי', en: 'Pallas\'s Grasshopper Warbler', sci: 'Helopsaltes certhiola', family: 'חרגולניים' },
  { he: 'חרגולן נחלים', en: 'River Warbler', sci: 'Locustella fluviatilis', family: 'חרגולניים' },
  { he: 'חרגולן זמירי', en: 'Savi\'s Warbler', sci: 'Locustella luscinioides', family: 'חרגולניים' },
  { he: 'חרגולן מנומר', en: 'Common Grasshopper Warbler', sci: 'Locustella naevia', family: 'חרגולניים' },
  { he: 'תפר', en: 'Zitting Cisticola', sci: 'Cisticola juncidis', family: 'סיסטיקוליים' },
  { he: 'פשוש', en: 'Graceful Prinia', sci: 'Prinia gracilis', family: 'סיסטיקוליים' },
  { he: 'סבכי שחור כיפה', en: 'Eurasian Blackcap', sci: 'Sylvia atricapilla', family: 'סבכיים' },
  { he: 'סבכי אפור', en: 'Garden Warbler', sci: 'Sylvia borin', family: 'סבכיים' },
  { he: 'סבכי ניצי', en: 'Barred Warbler', sci: 'Curruca nisoria', family: 'סבכיים' },
  { he: 'סבכי טוחנים', en: 'Lesser Whitethroat', sci: 'Curruca curruca', family: 'סבכיים' },
  { he: 'סבכי שיטים', en: 'Arabian Warbler', sci: 'Curruca leucomelaena', family: 'סבכיים' },
  { he: 'סבכי חורש', en: 'Eastern Orphean Warbler', sci: 'Curruca crassirostris', family: 'סבכיים' },
  { he: 'סבכי מדבר', en: 'Asian Desert Warbler', sci: 'Curruca nana', family: 'סבכיים' },
  { he: 'סבכי אשלים', en: 'Menetries\'s Warbler', sci: 'Curruca mystacea', family: 'סבכיים' },
  { he: 'סבכי שחור גרון', en: 'Rüppell\'s Warbler', sci: 'Curruca ruppeli', family: 'סבכיים' },
  { he: 'סבכי קפריסאי', en: 'Cyprus Warbler', sci: 'Curruca melanothorax', family: 'סבכיים' },
  { he: 'סבכי שחור ראש', en: 'Sardinian Warbler', sci: 'Curruca melanocephala', family: 'סבכיים' },
  { he: 'סבכי רונן', en: 'Eastern Subalpine Warbler', sci: 'Curruca cantillans', family: 'סבכיים' },
  { he: 'סבכי קוצים', en: 'Common Whitethroat', sci: 'Curruca communis', family: 'סבכיים' },
  { he: 'סבכי ערבות', en: 'Spectacled Warbler', sci: 'Curruca conspicillata', family: 'סבכיים' },
  { he: 'זנבן ערבי', en: 'Arabian Babbler', sci: 'Argya squamiceps', family: 'זנבניים' },
  { he: 'מלכילון לבן-גבות', en: 'Common Firecrest', sci: 'Regulus ignicapilla', family: 'מלכילוניים' },
  { he: 'מלכילון האורנים', en: 'Goldcrest', sci: 'Regulus regulus', family: 'מלכילוניים' },
  { he: 'גדרון מובהק', en: 'Eurasian Wren', sci: 'Troglodytes troglodytes', family: 'גדרוניים' },
  { he: 'סיטת צוקים', en: 'Western Rock Nuthatch', sci: 'Sitta neumayer', family: 'סיטיים' },
  { he: 'סיטה אירופית', en: 'Eurasian Nuthatch', sci: 'Sitta europaea', family: 'סיטיים' },
  { he: 'כותלי', en: 'Wallcreeper', sci: 'Tichodroma muraria', family: 'כותליים' },
  { he: 'מיינה מצויה', en: 'Common Myna', sci: 'Acridotheres tristis', family: 'זרזיריים' },
  { he: 'זרזיר בורמזי', en: 'Vinous-breasted Starling', sci: 'Acridotheres burmannicus', family: 'זרזיריים' },
  { he: 'זרזיר שחור קולר', en: 'Black-collared Starling', sci: 'Gracupica nigricollis', family: 'זרזיריים' },
  { he: 'זרזיר ארבה', en: 'Rosy Starling', sci: 'Pastor roseus', family: 'זרזיריים' },
  { he: 'זרזיר מצוי', en: 'Common Starling', sci: 'Sturnus vulgaris', family: 'זרזיריים' },
  { he: 'זרזיר סגול', en: 'Purple Starling', sci: 'Lamprotornis purpureus', family: 'זרזיריים' },
  { he: 'זרזיר הדור', en: 'Superb Starling', sci: 'Lamprotornis superbus', family: 'זרזיריים' },
  { he: 'זרזיר סגול-גב', en: 'Violet-backed Starling', sci: 'Cinnyricinclus leucogaster', family: 'זרזיריים' },
  { he: 'טריסטרמית', en: 'Tristram\'s Starling', sci: 'Onychognathus tristramii', family: 'זרזיריים' },
  { he: 'קיכלי רונן', en: 'Song Thrush', sci: 'Turdus philomelos', family: 'קיכליים' },
  { he: 'קיכלי גדול', en: 'Mistle Thrush', sci: 'Turdus viscivorus', family: 'קיכליים' },
  { he: 'קיכלי לבן-גבה', en: 'Redwing', sci: 'Turdus iliacus', family: 'קיכליים' },
  { he: 'שחרור', en: 'Common Blackbird', sci: 'Turdus merula', family: 'קיכליים' },
  { he: 'קיכלי אפור-חזה', en: 'Eyebrowed Thrush', sci: 'Turdus obscurus', family: 'קיכליים' },
  { he: 'קיכלי אפור', en: 'Fieldfare', sci: 'Turdus pilaris', family: 'קיכליים' },
  { he: 'קיכלי סהרון', en: 'Ring Ouzel', sci: 'Turdus torquatus', family: 'קיכליים' },
  { he: 'קיכלי שחור-גרון', en: 'Black-throated Thrush', sci: 'Turdus atrogularis', family: 'קיכליים' },
  { he: 'קיכלי אדום-גרון', en: 'Red-throated Thrush', sci: 'Turdus ruficollis', family: 'קיכליים' },
  { he: 'קיכלי חום-כנף', en: 'Dusky Thrush', sci: 'Turdus eunomus', family: 'קיכליים' },
  { he: 'חמריה שחורה', en: 'Black Scrub Robin', sci: 'Cercotrichas podobe', family: 'חטפיתיים' },
  { he: 'חמריה חלודת-זנב', en: 'Rufous-tailed Scrub Robin', sci: 'Cercotrichas galactotes', family: 'חטפיתיים' },
  { he: 'חטפית אפורה', en: 'Spotted Flycatcher', sci: 'Muscicapa striata', family: 'חטפיתיים' },
  { he: 'אדום-חזה', en: 'European Robin', sci: 'Erithacus rubecula', family: 'חטפיתיים' },
  { he: 'זמיר מנומר', en: 'Thrush Nightingale', sci: 'Luscinia luscinia', family: 'חטפיתיים' },
  { he: 'זמיר הירדן', en: 'Common Nightingale', sci: 'Luscinia megarhynchos', family: 'חטפיתיים' },
  { he: 'כחול חזה', en: 'Bluethroat', sci: 'Luscinia svecica', family: 'חטפיתיים' },
  { he: 'אירניה', en: 'White-throated Robin', sci: 'Irania gutturalis', family: 'חטפיתיים' },
  { he: 'כחול-זנב', en: 'Red-flanked Bluetail', sci: 'Tarsiger cyanurus', family: 'חטפיתיים' },
  { he: 'חטפית טאיגה', en: 'Taiga Flycatcher', sci: 'Ficedula albicilla', family: 'חטפיתיים' },
  { he: 'חטפית גמדית', en: 'Red-breasted Flycatcher', sci: 'Ficedula parva', family: 'חטפיתיים' },
  { he: 'חטפית טורקית', en: 'Semicollared Flycatcher', sci: 'Ficedula semitorquata', family: 'חטפיתיים' },
  { he: 'חטפית שחורת-עורף', en: 'European Pied Flycatcher', sci: 'Ficedula hypoleuca', family: 'חטפיתיים' },
  { he: 'חטפית לבנת-עורף', en: 'Collared Flycatcher', sci: 'Ficedula albicollis', family: 'חטפיתיים' },
  { he: 'חכלילית אדומת-גב', en: 'Eversmann\'s Redstart', sci: 'Phoenicurus erythronotus', family: 'חטפיתיים' },
  { he: 'חכלילית סלעים', en: 'Black Redstart', sci: 'Phoenicurus ochruros', family: 'חטפיתיים' },
  { he: 'חכלילית עצים', en: 'Common Redstart', sci: 'Phoenicurus phoenicurus', family: 'חטפיתיים' },
  { he: 'צוקית חכלילית', en: 'Common Rock Thrush', sci: 'Monticola saxatilis', family: 'חטפיתיים' },
  { he: 'צוקית בודדת', en: 'Blue Rock Thrush', sci: 'Monticola solitarius', family: 'חטפיתיים' },
  { he: 'דוחל חום גרון', en: 'Whinchat', sci: 'Saxicola rubetra', family: 'חטפיתיים' },
  { he: 'דוחל שחור-גרון', en: 'European Stonechat', sci: 'Saxicola rubicola', family: 'חטפיתיים' },
  { he: 'דוחל מזרחי', en: 'Siberian Stonechat', sci: 'Saxicola maurus', family: 'חטפיתיים' },
  { he: 'דוחל שחור', en: 'Pied Bush Chat', sci: 'Saxicola caprata', family: 'חטפיתיים' },
  { he: 'סלעית אירופאית', en: 'Northern Wheatear', sci: 'Oenanthe oenanthe', family: 'חטפיתיים' },
  { he: 'סלעית חלודת-שת', en: 'Kurdish Wheatear', sci: 'Oenanthe xanthoprymna', family: 'חטפיתיים' },
  { he: 'סלעית פרסית', en: 'Red-tailed Wheatear', sci: 'Oenanthe chrysopygia', family: 'חטפיתיים' },
  { he: 'שחור זנב', en: 'Blackstart', sci: 'Oenanthe melanura', family: 'חטפיתיים' },
  { he: 'סלעית הודית', en: 'Variable Wheatear', sci: 'Oenanthe picata', family: 'חטפיתיים' },
  { he: 'סלעית שחורה', en: 'Black Wheatear', sci: 'Oenanthe leucura', family: 'חטפיתיים' },
  { he: 'סלעית שחורת בטן', en: 'White-crowned Wheatear', sci: 'Oenanthe leucopyga', family: 'חטפיתיים' },
  { he: 'סלעית חורף', en: 'Finsch\'s Wheatear', sci: 'Oenanthe finschii', family: 'חטפיתיים' },
  { he: 'סלעית לבנת כנף', en: 'Mourning Wheatear', sci: 'Oenanthe lugens', family: 'חטפיתיים' },
  { he: 'סלעית ערבות', en: 'Isabelline Wheatear', sci: 'Oenanthe isabellina', family: 'חטפיתיים' },
  { he: 'סלעית נזירה', en: 'Hooded Wheatear', sci: 'Oenanthe monacha', family: 'חטפיתיים' },
  { he: 'סלעית מדבר', en: 'Desert Wheatear', sci: 'Oenanthe deserti', family: 'חטפיתיים' },
  { he: 'סלעית קפריסאית', en: 'Cyprus Wheatear', sci: 'Oenanthe cypriaca', family: 'חטפיתיים' },
  { he: 'סלעית שיחים', en: 'Pied Wheatear', sci: 'Oenanthe pleschanka', family: 'חטפיתיים' },
  { he: 'סלעית חלודת זנב', en: 'Red-rumped Wheatear', sci: 'Oenanthe moesta', family: 'חטפיתיים' },
  { he: 'צופית בוהקת', en: 'Palestine Sunbird', sci: 'Cinnyris osea', family: 'צופיתיים' },
  { he: 'דרורית קצרת-אצבעות', en: '', sci: '', family: '' },
  { he: 'בארית הרים', en: 'Rock Sparrow', sci: 'Petronia petronia', family: 'דרוריים' },
  { he: 'דרורית צהובת גרון', en: 'Yellow-throated Sparrow', sci: 'Gymnoris xanthocollis', family: 'דרוריים' },
  { he: 'דרור הרים', en: 'Eurasian Tree Sparrow', sci: 'Passer montanus', family: 'דרוריים' },
  { he: 'דרור ספרדי', en: 'Spanish Sparrow', sci: 'Passer hispaniolensis', family: 'דרוריים' },
  { he: 'דרור בית', en: 'House Sparrow', sci: 'Passer domesticus', family: 'דרוריים' },
  { he: 'דרור ערבי זהוב', en: 'Arabian Golden Sparrow', sci: 'Passer euchlorus', family: 'דרוריים' },
  { he: 'דרור הירדן', en: 'Dead Sea Sparrow', sci: 'Passer moabiticus', family: 'דרוריים' },
  { he: 'אורג-מסיכה דרומי', en: 'Southern Masked Weaver', sci: 'Ploceus velatus', family: 'אורגיים' },
  { he: 'כסוף מקור הודי', en: 'Indian Silverbill', sci: 'Euodice malabarica', family: 'אסטרילדיים' },
  { he: 'פרושית אדומה', en: 'Red Avadavat', sci: 'Amandava amandava', family: 'אסטרילדיים' },
  { he: 'סתרי צוקים', en: 'Alpine Accentor', sci: 'Prunella collaris', family: 'סתריים' },
  { he: 'סתרי ממושקף', en: 'Radde\'s Accentor', sci: 'Prunella ocularis', family: 'סתריים' },
  { he: 'סתרי שחור-גרון', en: 'Black-throated Accentor', sci: 'Prunella atrogularis', family: 'סתריים' },
  { he: 'סתרי מצוי', en: 'Dunnock', sci: 'Prunella modularis', family: 'סתריים' },
  { he: 'נחליאלי לימוני', en: 'Citrine Wagtail', sci: 'Motacilla citreola', family: 'נחליאליים' },
  { he: 'נחליאלי זנבתן', en: 'Grey Wagtail', sci: 'Motacilla cinerea', family: 'נחליאליים' },
  { he: 'נחליאלי לבן', en: 'White Wagtail', sci: 'Motacilla alba', family: 'נחליאליים' },
  { he: 'נחליאלי צהוב', en: 'Western Yellow Wagtail', sci: 'Motacilla flava', family: 'נחליאליים' },
  { he: 'פיפיון ארך רגליים', en: 'Richard\'s Pipit', sci: 'Anthus richardi', family: 'נחליאליים' },
  { he: 'פיפיון ערבות', en: 'Blyth\'s Pipit', sci: 'Anthus godlewskii', family: 'נחליאליים' },
  { he: 'פיפיון צהוב', en: 'Tawny Pipit', sci: 'Anthus campestris', family: 'נחליאליים' },
  { he: 'פיפיון הרים', en: 'Long-billed Pipit', sci: 'Anthus similis', family: 'נחליאליים' },
  { he: 'פיפיון שדות', en: 'Meadow Pipit', sci: 'Anthus pratensis', family: 'נחליאליים' },
  { he: 'פיפיון עצים', en: 'Tree Pipit', sci: 'Anthus trivialis', family: 'נחליאליים' },
  { he: 'פיפיון זיתי', en: 'Olive-backed Pipit', sci: 'Anthus hodgsoni', family: 'נחליאליים' },
  { he: 'פיפיון אדום-גרון', en: 'Red-throated Pipit', sci: 'Anthus cervinus', family: 'נחליאליים' },
  { he: 'פיפיון ממושקף', en: 'Buff-bellied Pipit', sci: 'Anthus rubescens', family: 'נחליאליים' },
  { he: 'פיפיון מים', en: 'Water Pipit', sci: 'Anthus spinoletta', family: 'נחליאליים' },
  { he: 'פרוש מצוי', en: 'Common Chaffinch', sci: 'Fringilla coelebs', family: 'פרושיים' },
  { he: 'פרוש הרים', en: 'Brambling', sci: 'Fringilla montifringilla', family: 'פרושיים' },
  { he: 'פצחן', en: 'Hawfinch', sci: 'Coccothraustes coccothraustes', family: 'פרושיים' },
  { he: 'חצוצרן חרמון', en: 'Asian Crimson-winged Finch', sci: 'Rhodopechys sanguineus', family: 'פרושיים' },
  { he: 'חצוצרן מדבר', en: 'Trumpeter Finch', sci: 'Bucanetes githagineus', family: 'פרושיים' },
  { he: 'ורדית אירופית', en: 'Common Rosefinch', sci: 'Carpodacus erythrinus', family: 'פרושיים' },
  { he: 'ורדית סיני', en: 'Sinai Rosefinch', sci: 'Carpodacus synoicus', family: 'פרושיים' },
  { he: 'ירקון', en: 'European Greenfinch', sci: 'Chloris chloris', family: 'פרושיים' },
  { he: 'חצוצרן שחור מקור', en: 'Desert Finch', sci: 'Rhodospiza obsoleta', family: 'פרושיים' },
  { he: 'תפוחית מצויה', en: 'Common Linnet', sci: 'Linaria cannabina', family: 'פרושיים' },
  { he: 'צלוב-מקור', en: 'Red Crossbill', sci: 'Loxia curvirostra', family: 'פרושיים' },
  { he: 'חוחית', en: 'European Goldfinch', sci: 'Carduelis carduelis', family: 'פרושיים' },
  { he: 'בזבוז אדום-מצח', en: 'Red-fronted Serin', sci: 'Serinus pusillus', family: 'פרושיים' },
  { he: 'בזבוז אירופאי', en: 'European Serin', sci: 'Serinus serinus', family: 'פרושיים' },
  { he: 'בזבוז הלבנון', en: 'Syrian Serin', sci: 'Serinus syriacus', family: 'פרושיים' },
  { he: 'חורפי', en: 'Eurasian Siskin', sci: 'Spinus spinus', family: 'פרושיים' },
  { he: 'גבתון שלג', en: 'Snow Bunting', sci: 'Plectrophenax nivalis', family: 'קלקרידיים' },
  { he: 'גבתון עפרוני', en: 'Corn Bunting', sci: 'Emberiza calandra', family: 'גיבתוניים' },
  { he: 'גבתון צהוב', en: 'Yellowhammer', sci: 'Emberiza citrinella', family: 'גיבתוניים' },
  { he: 'גבתון לבן כיפה', en: 'Pine Bunting', sci: 'Emberiza leucocephalos', family: 'גיבתוניים' },
  { he: 'גבתון סלעים', en: 'Rock Bunting', sci: 'Emberiza cia', family: 'גיבתוניים' },
  { he: 'גבתון אפור', en: 'Cinereous Bunting', sci: 'Emberiza cineracea', family: 'גיבתוניים' },
  { he: 'גבתון גנים', en: 'Ortolan Bunting', sci: 'Emberiza hortulana', family: 'גיבתוניים' },
  { he: 'גבתון חום-ראש', en: 'Red-headed Bunting', sci: 'Emberiza bruniceps', family: 'גיבתוניים' },
  { he: 'גיבתון סוף', en: 'Common Reed Bunting', sci: 'Emberiza schoeniclus', family: 'גיבתוניים' },
  { he: 'גבתון אדום מקור', en: 'Cretzschmar\'s Bunting', sci: 'Emberiza caesia', family: 'גיבתוניים' },
  { he: 'גבתון מדבר', en: 'Striolated Bunting', sci: 'Emberiza striolata', family: 'גיבתוניים' },
  { he: 'גבתון גמד', en: 'Little Bunting', sci: 'Emberiza pusilla', family: 'גיבתוניים' },
  { he: 'גבתון לבן-גרון', en: 'Rustic Bunting', sci: 'Emberiza rustica', family: 'גיבתוניים' },
  { he: 'גבתון צווארון', en: 'Yellow-breasted Bunting', sci: 'Emberiza aureola', family: 'גיבתוניים' },
  { he: 'גבתון שחור ראש', en: 'Black-headed Bunting', sci: 'Emberiza melanocephala', family: 'גיבתוניים' },
];

export const SPECIES_DETAILS = Object.fromEntries(SPECIES_DATA.map((s) => [s.he, s]));
